version: '3.3'

services:
  node:
    image: node:latest
    ports:
      - "443:443"
    volumes:
      - /opt/TipocaCity/kamino-frontend/:/opt/kamino
    networks:
      - webnet
    depends_on:
      - api
    working_dir: /opt/kamino
    command: sh -c 'npm i && npm run -- dev'

  api:
    image: golang:latest
    ports:
      - "8080:8080"
    networks:
      - webnet
    # Here you can mount the directory where your Go API code is located
    volumes:
      - /opt/TipocaCity/cyclone:/opt/cyclone
    working_dir: /opt/cyclone
    command: 
      - /bin/bash
      - -c 
      - | 
        dpkg -i ./powershell-deb/packages-microsoft-prod.deb
        apt update 
        apt install powershell -y
        pwsh -c "Install-Module -Name BruhArmy -Force"
        pwsh -c "Install-Module -Name VMware.PowerCLI -Force"
        pwsh -c "Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:\$false"
        pwsh -c "Set-PowerCLIConfiguration -ParticipateInCEIP:\$false -Confirm:\$false"
        pwsh -c '$$cred = Get-Content ./config.conf | Select-String vCenterUsername -Context 0,1; $$password = ConvertTo-SecureString -String $$cred.toString().split(' ')[8].Substring(1, $$cred.toString().split(' ')[8].length - 2) -AsPlainText -Force; [PSCredential]::New($$cred.toString().split(' ')[3].trim(), ($$password)) | Export-Clixml -Path ./lib/creds/vsphere_cred.xml'
        go run .

  ldap:
    image: osixia/openldap:latest
    environment:
      LDAP_ORGANISATION: "Kamino Labs"
      LDAP_DOMAIN: "kamino.labs"
      LDAP_ADMIN_PASSWORD: "changeme"
    networks:
      - webnet
    # LDAP needs a volume to persist data
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_slapd:/etc/ldap/slapd.d

networks:
  webnet:

volumes:
  ldap_data:
  ldap_slapd: