version: '3.3'

services:
  node:
    image: node:latest
    restart: always
    ports:
      - "443:443"
    volumes:
      - /opt/TipocaCity/kamino-frontend/:/opt/kamino
    networks:
      - tipoca
    depends_on:
      - api
    working_dir: /opt/kamino
    command: sh -c 'npm i && npm run -- dev'
    
  api:
    image: golang:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - tipoca
    # Here you can mount the directory where your Go API code is located
    volumes:
      - /opt/TipocaCity/cyclone:/opt/cyclone
    working_dir: /opt/cyclone
    command: 
      - /bin/bash
      - -c 
      - | 
        export vcenterpassword='$vcenterpassword'
        export vcenterusername='$vcenterusername'
        export vcenterurl='$vcenterurl'
        export parentresourcepool='$parentresourcepool'
        export presettemplateresourcepool='$presettemplateresourcepool'
        export targetresourcepool='$targetresourcepool'
        export cluster='$cluster'
        export inventorylocation='$inventorylocation'
        export pfsensepassword='$pfsensepassword'
        export templatelocation='$templatelocation'
        export datacenter='$datacenter'
        dpkg -i ./powershell-deb/packages-microsoft-prod.deb
        apt update 
        apt install powershell ldap-utils -y
        pwsh -ExecutionPolicy Unrestricted -f ./pwsh/install/install.ps1
        pwsh -ExecutionPolicy Unrestricted -f ./pwsh/install/vsphere-prep.ps1
        cp -r ./pwsh/Kamino /root/.local/share/powershell/Modules/
        unset vcenterpassword
        unset vcenterusername
        unset vcenterurl
        unset parentresourcepool
        unset presettemplateresourcepool
        unset targetresourcepool
        unset cluster
        unset inventorylocation
        unset pfsensepassword
        unset templatelocation
        unset datacenter
        go run .

  ldap:
    image: osixia/openldap:latest
    restart: always
    ports:
      - "389:389"
    environment:
      LDAP_ORGANISATION: "Kamino Labs"
      LDAP_DOMAIN: "kamino.labs"
      LDAP_ADMIN_PASSWORD: "$ldapadminpassword"
    networks:
      - tipoca
    # LDAP needs a volume to persist data
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_slapd:/etc/ldap/slapd.d

networks:
  tipoca:

volumes:
  ldap_data:
  ldap_slapd: